<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "csp_editor"
 * Auto generated by Extension Builder 2021-07-06
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Csp-Editor',
    'description' => 'CSP Editor',
    'category' => 'plugin',
    'author' => 'Timo Feuerstein',
    'author_email' => 'timo.feuerstein@renolit.com',
    'state' => 'stable',
    'version' => '10.4.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
            'php' => '7.2.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
